services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5400:5432"
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data:
