services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5400:5432"
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi_cipher
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8080:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - my_network
    volumes:
      - logs:/app/logs

  redis:
    container_name: redis_cipher
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

  celery:
    container_name: celery_cipher
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.services.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - my_network
    volumes:
      - logs:/app/logs

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data:
  logs:
