"""add admin status

Revision ID: cee48721c4af
Revises: 0a7e59a5f47f
Create Date: 2024-11-09 16:58:57.123553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee48721c4af'
down_revision: Union[str, None] = '0a7e59a5f47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postUser')
    op.add_column('post', sa.Column('address', sa.String(), nullable=False))
    op.alter_column('post', 'isApproved',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    op.alter_column('post', 'isApproved',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('post', 'address')
    op.create_table('postUser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idPost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idPost'], ['post.id'], name='postUser_idPost_fkey'),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='postUser_idUser_fkey'),
    sa.PrimaryKeyConstraint('id', name='postUser_pkey')
    )
    # ### end Alembic commands ###
