"""init2

Revision ID: d903d955503a
Revises: f8b18c4eed9e
Create Date: 2024-09-13 13:59:30.236796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd903d955503a'
down_revision: Union[str, None] = 'f8b18c4eed9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idPost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPost'], ['post.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postUser')
    # ### end Alembic commands ###
